# 1. Create an array to store 5 names. Have the user enter in the 5 names and then print out the 5 names in all UPPERCASE all on the same line. Note that the user may not enter all the names in uppercase.

# names = []
# 5.times do |i|
#   print "Enter a name: "
#   names[i] = gets.chomp.upcase
# end
#
# puts names.join(' ')

# 2. Create an array to store 3 boolean values entered in by the user. Print out YES if all the values are true and NO if at least one value is false.

# boolean = []
# boolean_print = "YES"
#
# 3.times do |i|
#   print "Enter true or false: "
#   boolean[i] = gets.chomp.downcase
#   if boolean[i] == "true"
#     boolean[i] = true
#   else
#     boolean[i] = false
#   end
# end
#
# if boolean.include?(false)
#   boolean_print = "NO"
# end
#
# puts boolean_print

# 3. Create an array to store the following words: firetruck, fire drill, fire hydrant, firefighter, fireproof, fire station, fire hose. Then write code that uses the array to print out truck, drill, hydrant, fighter, proof, station, hose without modifying the array.

# fire_array = ["firetruck", "fire drill", "fire hydrant", "firefighter", "fireproof", "fire station", "fire hose"]
#
# fire_array.length.times do |i|
#   puts fire_array[i].slice!("fire")
#   puts fire_array[i]
# end
#
# puts fire_array

# 4. Create an array to store the amount of money spent on 4 people during the Holidays. Have the user enter in the amount spent on each person. Print the total spent on all the people. Total money spent should be displayed with a dollar sign, decimal point, and only 2 digits after the decimal.

# money_spent = []
# people = ["Jenny", "John", "Roberta", "Max"]
# total = 0
#
# 4.times do |i|
#   print "How much was spent on #{people[i]}? "
#   money_spent[i] = gets.chomp.to_f
#   total += money_spent[i]
# end
#
# puts "$#{total.round(2)}"

# 5. Create an array to store 5 random numbers (between 1 and 10, including both 1 and 10) generated by the computer. Print out the square of each of the elements in the array.

# random_numbers = []
#
# 5.times do |i|
#   random_numbers[i] = rand(1..10)
#   puts random_numbers[i] * random_numbers[i]
# end

# 6. Create an array to store 5000 decimal numbers. Randomly generate numbers from between 0 – 1 (including 0, but not including 1) to fill the array. Calculate and print the mean of all the elements in the array.

# giant_array = []
# total = 0
#
# 5000.times do |i|
#   giant_array[i] = rand()
#   total += giant_array[i]
# end
#
# puts total / giant_array.length

# 7. Create an array of people that are invited to a party. Allow the user to ask if a certain person is invited to the party. If the person is on the invitation list respond INVITED otherwise respond NOT INVITED.

# party_people = ["Nadia", "Jennifer", "Rachel", "Jessica", "Beth", "Hailey", "Ari", "Drea", "Taarna", "Skye", "Johanna"]
#
# print "Who should we check the party list for? "
# party_check = gets.chomp.capitalize
#
# if party_people.include?(party_check)
#   puts "INVITED"
# else
#   puts "NOT INVITED"
# end

# 8. Have the user enter in a sentence. Then, using an array, store the frequency of each letter of the alphabet from the sentence. Print out the frequency of each letter. Do not count uppercase and lowercase letters differently.

print "Enter a sentence: "
sentence = gets.chomp.upcase.delete(' ')
alphabet = Array.new(26, 0)

sentence.length.times do |i|
  alphabet[sentence[i].ord - 65] += 1
end

puts alphabet
